In [1]:
import pandas as pd
import numpy as np

In [398]:
fb = pd.read_csv("eng1_2122_shooting_Data.csv")
fb

Date          Squad Home_Away  Match_Half Minute  \
0     2021-08-13      Brentford      Home           1     11   
1     2021-08-13      Brentford      Home           1     12   
2     2021-08-13      Brentford      Home           1     22   
3     2021-08-13      Brentford      Home           1     28   
4     2021-08-13      Brentford      Home           1     30   
5     2021-08-13      Brentford      Home           2     66   
6     2021-08-13      Brentford      Home           2     73   
7     2021-08-13      Brentford      Home           2     80   
8     2021-08-13        Arsenal      Away           1      2   
9     2021-08-13        Arsenal      Away           1     16   
10    2021-08-13        Arsenal      Away           1     31   
11    2021-08-13        Arsenal      Away           1     33   
12    2021-08-13        Arsenal      Away           1     38   
13    2021-08-13        Arsenal      Away           1     42   
14    2021-08-13        Arsenal      Away           1   45+1   
15    2021-08-13        Arsenal      Away           2     51   
16    2021-08-13        Arsenal      Away           2     60   
17    2021-08-13        Arsenal      Away           2     64   
18    2021-08-13        Arsenal      Away           2     65   
19    2021-08-13        Arsenal      Away           2     68   
20    2021-08-13        Arsenal      Away           2     70   
21    2021-08-13        Arsenal      Away           2     76   
22    2021-08-13        Arsenal      Away           2     77   
23    2021-08-13        Arsenal      Away           2     83   
24    2021-08-13        Arsenal      Away           2     86   
25    2021-08-13        Arsenal      Away           2     87   
26    2021-08-13        Arsenal      Away           2     87   
27    2021-08-13        Arsenal      Away           2   90+1   
28    2021-08-13        Arsenal      Away           2   90+2   
29    2021-08-13        Arsenal      Away           2   90+2   
...          ...            ...       ...         ...    ...   
9754  2022-05-22  Newcastle Utd      Away           2     60   
9755  2022-05-22  Newcastle Utd      Away           2     85   
9756  2022-05-22  Newcastle Utd      Away           2     90   
9757  2022-05-22        Chelsea      Home           1      5   
9758  2022-05-22        Chelsea      Home           1      9   
9759  2022-05-22        Chelsea      Home           1      9   
9760  2022-05-22        Chelsea      Home           1      9   
9761  2022-05-22        Chelsea      Home           1     11   
9762  2022-05-22        Chelsea      Home           1     15   
9763  2022-05-22        Chelsea      Home           1     21   
9764  2022-05-22        Chelsea      Home           1     39   
9765  2022-05-22        Chelsea      Home           1     40   
9766  2022-05-22        Chelsea      Home           1     44   
9767  2022-05-22        Chelsea      Home           1   45+1   
9768  2022-05-22        Chelsea      Home           2     63   
9769  2022-05-22        Chelsea      Home           2     64   
9770  2022-05-22        Chelsea      Home           2     70   
9771  2022-05-22        Chelsea      Home           2     71   
9772  2022-05-22        Chelsea      Home           2     81   
9773  2022-05-22        Chelsea      Home           2     83   
9774  2022-05-22        Chelsea      Home           2   90+1   
9775  2022-05-22        Chelsea      Home           2   90+3   
9776  2022-05-22        Watford      Away           1     14   
9777  2022-05-22        Watford      Away           1     25   
9778  2022-05-22        Watford      Away           1     25   
9779  2022-05-22        Watford      Away           1     31   
9780  2022-05-22        Watford      Away           2     48   
9781  2022-05-22        Watford      Away           2     50   
9782  2022-05-22        Watford      Away           2     80   
9783  2022-05-22        Watford      Away           2     87   

           Shooting_Player     Outcome  Dis

In [3]:
list(fb.columns)

['Date',
 'Squad',
 'Home_Away',
 'Match_Half',
 'Minute',
 'Shooting_Player',
 'Outcome',
 'Distance',
 'Body_Part',
 'Shot_Notes',
 'SCA1_Player',
 'SCA1_Event',
 'SCA2_Player',
 'SCA2_Event']

In [4]:
us = pd.read_csv("eng1_2122_shooting_Data_understat.csv")
us

league      id  minute       result      X      Y        xG  \
0       EPL  425564      10  MissedShots  0.913  0.539  0.053464   
1       EPL  425565      11   ShotOnPost  0.908  0.315  0.118297   
2       EPL  425567      21         Goal  0.874  0.698  0.052145   
3       EPL  425568      27  MissedShots  0.812  0.478  0.065706   
4       EPL  425569      29  MissedShots  0.892  0.357  0.080691   
5       EPL  425579      65    SavedShot  0.882  0.332  0.072584   
6       EPL  425582      72         Goal  0.969  0.481  0.886598   
7       EPL  425585      79  MissedShots  0.973  0.528  0.558696   
8       EPL  425563       1    SavedShot  0.715  0.532  0.017222   
9       EPL  425566      15  MissedShots  0.847  0.312  0.025566   
10      EPL  425570      30  MissedShots  0.916  0.515  0.096495   
11      EPL  425571      32  MissedShots  0.819  0.270  0.024410   
12      EPL  425572      37  MissedShots  0.825  0.748  0.019192   
13      EPL  425573      41  MissedShots  0.905  0.518  0.041767   
14      EPL  425574      45  BlockedShot  0.862  0.371  0.051384   
15      EPL  425575      50    SavedShot  0.852  0.550  0.071917   
16      EPL  425576      59    SavedShot  0.748  0.369  0.017827   
17      EPL  425577      63  BlockedShot  0.860  0.666  0.044574   
18      EPL  425578      64  MissedShots  0.966  0.567  0.121241   
19      EPL  425580      66  BlockedShot  0.812  0.343  0.036226   
20      EPL  425581      69  MissedShots  0.888  0.634  0.055561   
21      EPL  425583      75  MissedShots  0.892  0.670  0.091006   
22      EPL  425584      76  MissedShots  0.807  0.767  0.050919   
23      EPL  425586      82  MissedShots  0.772  0.287  0.014195   
24      EPL  425587      85  MissedShots  0.748  0.429  0.018808   
25      EPL  425588      86    SavedShot  0.865  0.599  0.085683   
26      EPL  425589      86  MissedShots  0.953  0.409  0.031568   
27      EPL  425590      90  MissedShots  0.706  0.549  0.010266   
28      EPL  425591      91  BlockedShot  0.837  0.463  0.037434   
29      EPL  425592      91  MissedShots  0.875  0.342  0.060589   
...     ...     ...     ...          ...    ...    ...       ...   
9745    EPL  477939      41  MissedShots  0.732  0.416  0.020920   
9746    EPL  477951      68         Goal  0.856  0.623  0.079920   
9747    EPL  477967      22  MissedShots  0.800  0.563  0.037256   
9748    EPL  477970      39  BlockedShot  0.849  0.539  0.083545   
9749    EPL  477971      40  BlockedShot  0.785  0.620  0.031684   
9750    EPL  477972      42  MissedShots  0.886  0.565  0.013365   
9751    EPL  477975      45  BlockedShot  0.853  0.298  0.034504   
9752    EPL  477977      54  MissedShots  0.916  0.461  0.054586   
9753    EPL  477978      56  BlockedShot  0.857  0.315  0.031173   
9754    EPL  477979      56  MissedShots  0.768  0.558  0.014911   
9755    EPL  477988      88  MissedShots  0.859  0.544  0.010228   
9756    EPL  477961       2  BlockedShot  0.829  0.697  0.027816   
9757    EPL  477962       6  MissedShots  0.895  0.598  0.138847   
9758    EPL  477963       8    SavedShot  0.842  0.469  0.065680   
9759    EPL  477964      10    SavedShot  0.954  0.355  0.097947   
9760    EPL  477965      11  BlockedShot  0.851  0.443  0.051858   
9761    EPL  477966      15         Goal  0.894  0.513  0.426137   
9762    EPL  477968      31         Goal  0.924  0.458  0.374078   
9763    EPL  477969      33  MissedShots  0.822  0.564  0.136766   
9764    EPL  477973      44    SavedShot  0.755  0.651  0.021562   
9765    EPL  477974      45    SavedShot  0.904  0.419  0.048551   
9766    EPL  477976      54    SavedShot  0.905  0.629  0.104051   
9767    EPL  477980      59    SavedShot  0.933  0.497  0.570549   
9768    EPL  477981      59  MissedShots  0.967  0.503  0.902710   
9769    EPL  477982      61  BlockedShot  0.928  0.358  0.523128   
9770    EPL  477983      63         Goal  0.894  0.289  0.075722   
9771    EPL  477984      69    SavedShot  0.852  0.482  0.332

### team name

In [5]:
np.sort(fb['Squad'].unique())

array(['Arsenal', 'Aston Villa', 'Brentford', 'Brighton', 'Burnley',
       'Chelsea', 'Crystal Palace', 'Everton', 'Leeds United',
       'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd',
       'Newcastle Utd', 'Norwich City', 'Southampton', 'Tottenham',
       'Watford', 'West Ham', 'Wolves'], dtype=object)

In [6]:
np.sort(us['home_team'].unique())

array(['Arsenal', 'Aston Villa', 'Brentford', 'Brighton', 'Burnley',
       'Chelsea', 'Crystal Palace', 'Everton', 'Leeds', 'Leicester',
       'Liverpool', 'Manchester City', 'Manchester United',
       'Newcastle United', 'Norwich', 'Southampton', 'Tottenham',
       'Watford', 'West Ham', 'Wolverhampton Wanderers'], dtype=object)

In [7]:
us = us.replace({'Leeds' : 'Leeds United', 'Leicester' : 'Leicester City', 'Manchester United' : 'Manchester Utd',
                 'Newcastle United' : 'Newcastle Utd', 'Norwich' : 'Norwich City', 'Wolverhampton Wanderers' : 'Wolves'})
us

league      id  minute       result      X      Y        xG  \
0       EPL  425564      10  MissedShots  0.913  0.539  0.053464   
1       EPL  425565      11   ShotOnPost  0.908  0.315  0.118297   
2       EPL  425567      21         Goal  0.874  0.698  0.052145   
3       EPL  425568      27  MissedShots  0.812  0.478  0.065706   
4       EPL  425569      29  MissedShots  0.892  0.357  0.080691   
5       EPL  425579      65    SavedShot  0.882  0.332  0.072584   
6       EPL  425582      72         Goal  0.969  0.481  0.886598   
7       EPL  425585      79  MissedShots  0.973  0.528  0.558696   
8       EPL  425563       1    SavedShot  0.715  0.532  0.017222   
9       EPL  425566      15  MissedShots  0.847  0.312  0.025566   
10      EPL  425570      30  MissedShots  0.916  0.515  0.096495   
11      EPL  425571      32  MissedShots  0.819  0.270  0.024410   
12      EPL  425572      37  MissedShots  0.825  0.748  0.019192   
13      EPL  425573      41  MissedShots  0.905  0.518  0.041767   
14      EPL  425574      45  BlockedShot  0.862  0.371  0.051384   
15      EPL  425575      50    SavedShot  0.852  0.550  0.071917   
16      EPL  425576      59    SavedShot  0.748  0.369  0.017827   
17      EPL  425577      63  BlockedShot  0.860  0.666  0.044574   
18      EPL  425578      64  MissedShots  0.966  0.567  0.121241   
19      EPL  425580      66  BlockedShot  0.812  0.343  0.036226   
20      EPL  425581      69  MissedShots  0.888  0.634  0.055561   
21      EPL  425583      75  MissedShots  0.892  0.670  0.091006   
22      EPL  425584      76  MissedShots  0.807  0.767  0.050919   
23      EPL  425586      82  MissedShots  0.772  0.287  0.014195   
24      EPL  425587      85  MissedShots  0.748  0.429  0.018808   
25      EPL  425588      86    SavedShot  0.865  0.599  0.085683   
26      EPL  425589      86  MissedShots  0.953  0.409  0.031568   
27      EPL  425590      90  MissedShots  0.706  0.549  0.010266   
28      EPL  425591      91  BlockedShot  0.837  0.463  0.037434   
29      EPL  425592      91  MissedShots  0.875  0.342  0.060589   
...     ...     ...     ...          ...    ...    ...       ...   
9745    EPL  477939      41  MissedShots  0.732  0.416  0.020920   
9746    EPL  477951      68         Goal  0.856  0.623  0.079920   
9747    EPL  477967      22  MissedShots  0.800  0.563  0.037256   
9748    EPL  477970      39  BlockedShot  0.849  0.539  0.083545   
9749    EPL  477971      40  BlockedShot  0.785  0.620  0.031684   
9750    EPL  477972      42  MissedShots  0.886  0.565  0.013365   
9751    EPL  477975      45  BlockedShot  0.853  0.298  0.034504   
9752    EPL  477977      54  MissedShots  0.916  0.461  0.054586   
9753    EPL  477978      56  BlockedShot  0.857  0.315  0.031173   
9754    EPL  477979      56  MissedShots  0.768  0.558  0.014911   
9755    EPL  477988      88  MissedShots  0.859  0.544  0.010228   
9756    EPL  477961       2  BlockedShot  0.829  0.697  0.027816   
9757    EPL  477962       6  MissedShots  0.895  0.598  0.138847   
9758    EPL  477963       8    SavedShot  0.842  0.469  0.065680   
9759    EPL  477964      10    SavedShot  0.954  0.355  0.097947   
9760    EPL  477965      11  BlockedShot  0.851  0.443  0.051858   
9761    EPL  477966      15         Goal  0.894  0.513  0.426137   
9762    EPL  477968      31         Goal  0.924  0.458  0.374078   
9763    EPL  477969      33  MissedShots  0.822  0.564  0.136766   
9764    EPL  477973      44    SavedShot  0.755  0.651  0.021562   
9765    EPL  477974      45    SavedShot  0.904  0.419  0.048551   
9766    EPL  477976      54    SavedShot  0.905  0.629  0.104051   
9767    EPL  477980      59    SavedShot  0.933  0.497  0.570549   
9768    EPL  477981      59  MissedShots  0.967  0.503  0.902710   
9769    EPL  477982      61  BlockedShot  0.928  0.358  0.523128   
9770    EPL  477983      63         Goal  0.894  0.289  0.075722   
9771    EPL  477984      69    SavedShot  0.852  0.482  0.332

### Check Match Order

In [194]:
fb_order = fb[['Date', 'Squad', 'Home_Away']].drop_duplicates().reset_index().drop(columns = ['index'])
fb_order

Date            Squad Home_Away
0    2021-08-13        Brentford      Home
1    2021-08-13          Arsenal      Away
2    2021-08-14   Manchester Utd      Away
3    2021-08-14     Leeds United      Away
4    2021-08-14   Leicester City      Home
5    2021-08-14           Wolves      Away
6    2021-08-14          Burnley      Home
7    2021-08-14         Brighton      Away
8    2021-08-14          Chelsea      Home
9    2021-08-14   Crystal Palace      Away
10   2021-08-14          Watford      Home
11   2021-08-14      Aston Villa      Away
12   2021-08-14          Everton      Home
13   2021-08-14      Southampton      Away
14   2021-08-14     Norwich City      Home
15   2021-08-14        Liverpool      Away
16   2021-08-15    Newcastle Utd      Away
17   2021-08-15         West Ham      Away
18   2021-08-15        Tottenham      Away
19   2021-08-15  Manchester City      Away
20   2021-08-21        Liverpool      Home
21   2021-08-21          Burnley      Away
22   2021-08-21      Aston Villa      Home
23   2021-08-21    Newcastle Utd      Away
24   2021-08-21  Manchester City      Home
25   2021-08-21     Norwich City      Away
26   2021-08-21     Leeds United      Home
27   2021-08-21          Everton      Away
28   2021-08-21   Crystal Palace      Home
29   2021-08-21        Brentford      Away
..          ...              ...       ...
730  2022-05-16    Newcastle Utd      Away
731  2022-05-16          Arsenal      Away
732  2022-05-17      Southampton      Home
733  2022-05-17        Liverpool      Away
734  2022-05-19          Everton      Home
735  2022-05-19   Crystal Palace      Away
736  2022-05-19      Aston Villa      Home
737  2022-05-19          Burnley      Away
738  2022-05-19          Chelsea      Home
739  2022-05-19   Leicester City      Away
740  2022-05-22        Brentford      Home
741  2022-05-22     Leeds United      Away
742  2022-05-22   Leicester City      Home
743  2022-05-22      Southampton      Away
744  2022-05-22   Crystal Palace      Home
745  2022-05-22   Manchester Utd      Away
746  2022-05-22          Arsenal      Home
747  2022-05-22          Everton      Away
748  2022-05-22         Brighton      Away
749  2022-05-22         West Ham      Away
750  2022-05-22     Norwich City      Home
751  2022-05-22        Tottenham      Away
752  2022-05-22  Manchester City      Home
753  2022-05-22      Aston Villa      Away
754  2022-05-22        Liverpool      Home
755  2022-05-22           Wolves      Away
756  2022-05-22          Burnley      Home
757  2022-05-22    Newcastle Utd      Away
758  2022-05-22          Chelsea      Home
759  2022-05-22          Watford      Away

[760 rows x 3 columns]

In [14]:
fb_order['Home_Away'].describe()

count      760
unique       2
top       Away
freq       494
Name: Home_Away, dtype: object

In [22]:
ha = []
for index, row in fb_order.iterrows():
    if index % 2 == 0:
        ha.append('Home')
    else:
        ha.append('Away')
        
ha

['Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 'Away',
 'Home',
 

In [195]:
fb_order = fb_order.drop(columns = ['Home_Away'])
fb_order = pd.concat([fb_order, pd.DataFrame(ha, columns = {'Home_Away'})], axis = 1)
fb_order

Date            Squad Home_Away
0    2021-08-13        Brentford      Home
1    2021-08-13          Arsenal      Away
2    2021-08-14   Manchester Utd      Home
3    2021-08-14     Leeds United      Away
4    2021-08-14   Leicester City      Home
5    2021-08-14           Wolves      Away
6    2021-08-14          Burnley      Home
7    2021-08-14         Brighton      Away
8    2021-08-14          Chelsea      Home
9    2021-08-14   Crystal Palace      Away
10   2021-08-14          Watford      Home
11   2021-08-14      Aston Villa      Away
12   2021-08-14          Everton      Home
13   2021-08-14      Southampton      Away
14   2021-08-14     Norwich City      Home
15   2021-08-14        Liverpool      Away
16   2021-08-15    Newcastle Utd      Home
17   2021-08-15         West Ham      Away
18   2021-08-15        Tottenham      Home
19   2021-08-15  Manchester City      Away
20   2021-08-21        Liverpool      Home
21   2021-08-21          Burnley      Away
22   2021-08-21      Aston Villa      Home
23   2021-08-21    Newcastle Utd      Away
24   2021-08-21  Manchester City      Home
25   2021-08-21     Norwich City      Away
26   2021-08-21     Leeds United      Home
27   2021-08-21          Everton      Away
28   2021-08-21   Crystal Palace      Home
29   2021-08-21        Brentford      Away
..          ...              ...       ...
730  2022-05-16    Newcastle Utd      Home
731  2022-05-16          Arsenal      Away
732  2022-05-17      Southampton      Home
733  2022-05-17        Liverpool      Away
734  2022-05-19          Everton      Home
735  2022-05-19   Crystal Palace      Away
736  2022-05-19      Aston Villa      Home
737  2022-05-19          Burnley      Away
738  2022-05-19          Chelsea      Home
739  2022-05-19   Leicester City      Away
740  2022-05-22        Brentford      Home
741  2022-05-22     Leeds United      Away
742  2022-05-22   Leicester City      Home
743  2022-05-22      Southampton      Away
744  2022-05-22   Crystal Palace      Home
745  2022-05-22   Manchester Utd      Away
746  2022-05-22          Arsenal      Home
747  2022-05-22          Everton      Away
748  2022-05-22         Brighton      Home
749  2022-05-22         West Ham      Away
750  2022-05-22     Norwich City      Home
751  2022-05-22        Tottenham      Away
752  2022-05-22  Manchester City      Home
753  2022-05-22      Aston Villa      Away
754  2022-05-22        Liverpool      Home
755  2022-05-22           Wolves      Away
756  2022-05-22          Burnley      Home
757  2022-05-22    Newcastle Utd      Away
758  2022-05-22          Chelsea      Home
759  2022-05-22          Watford      Away

[760 rows x 3 columns]

In [196]:
fb_order = pd.concat([fb_order, pd.DataFrame(np.repeat(list(range(0, 380)), 2), columns = {'order'})], axis = 1)
fb_order

Date            Squad Home_Away  order
0    2021-08-13        Brentford      Home      0
1    2021-08-13          Arsenal      Away      0
2    2021-08-14   Manchester Utd      Home      1
3    2021-08-14     Leeds United      Away      1
4    2021-08-14   Leicester City      Home      2
5    2021-08-14           Wolves      Away      2
6    2021-08-14          Burnley      Home      3
7    2021-08-14         Brighton      Away      3
8    2021-08-14          Chelsea      Home      4
9    2021-08-14   Crystal Palace      Away      4
10   2021-08-14          Watford      Home      5
11   2021-08-14      Aston Villa      Away      5
12   2021-08-14          Everton      Home      6
13   2021-08-14      Southampton      Away      6
14   2021-08-14     Norwich City      Home      7
15   2021-08-14        Liverpool      Away      7
16   2021-08-15    Newcastle Utd      Home      8
17   2021-08-15         West Ham      Away      8
18   2021-08-15        Tottenham      Home      9
19   2021-08-15  Manchester City      Away      9
20   2021-08-21        Liverpool      Home     10
21   2021-08-21          Burnley      Away     10
22   2021-08-21      Aston Villa      Home     11
23   2021-08-21    Newcastle Utd      Away     11
24   2021-08-21  Manchester City      Home     12
25   2021-08-21     Norwich City      Away     12
26   2021-08-21     Leeds United      Home     13
27   2021-08-21          Everton      Away     13
28   2021-08-21   Crystal Palace      Home     14
29   2021-08-21        Brentford      Away     14
..          ...              ...       ...    ...
730  2022-05-16    Newcastle Utd      Home    365
731  2022-05-16          Arsenal      Away    365
732  2022-05-17      Southampton      Home    366
733  2022-05-17        Liverpool      Away    366
734  2022-05-19          Everton      Home    367
735  2022-05-19   Crystal Palace      Away    367
736  2022-05-19      Aston Villa      Home    368
737  2022-05-19          Burnley      Away    368
738  2022-05-19          Chelsea      Home    369
739  2022-05-19   Leicester City      Away    369
740  2022-05-22        Brentford      Home    370
741  2022-05-22     Leeds United      Away    370
742  2022-05-22   Leicester City      Home    371
743  2022-05-22      Southampton      Away    371
744  2022-05-22   Crystal Palace      Home    372
745  2022-05-22   Manchester Utd      Away    372
746  2022-05-22          Arsenal      Home    373
747  2022-05-22          Everton      Away    373
748  2022-05-22         Brighton      Home    374
749  2022-05-22         West Ham      Away    374
750  2022-05-22     Norwich City      Home    375
751  2022-05-22        Tottenham      Away    375
752  2022-05-22  Manchester City      Home    376
753  2022-05-22      Aston Villa      Away    376
754  2022-05-22        Liverpool      Home    377
755  2022-05-22           Wolves      Away    377
756  2022-05-22          Burnley      Home    378
757  2022-05-22    Newcastle Utd      Away    378
758  2022-05-22          Chelsea      Home    379
759  2022-05-22          Watford      Away    379

[760 rows x 4 columns]

In [112]:
us_order = us[['date', 'home_team', 'away_team', 'match_id']].drop_duplicates().reset_index().drop(columns = ['index'])
us_order

date        home_team        away_team  match_id
0    2021-08-13 19:00:00        Brentford          Arsenal     16376
1    2021-08-14 11:30:00   Manchester Utd     Leeds United     16377
2    2021-08-14 14:00:00          Burnley         Brighton     16378
3    2021-08-14 14:00:00          Chelsea   Crystal Palace     16379
4    2021-08-14 14:00:00          Everton      Southampton     16380
5    2021-08-14 14:00:00   Leicester City           Wolves     16381
6    2021-08-14 14:00:00          Watford      Aston Villa     16382
7    2021-08-14 16:30:00     Norwich City        Liverpool     16383
8    2021-08-15 13:00:00    Newcastle Utd         West Ham     16384
9    2021-08-15 15:30:00        Tottenham  Manchester City     16385
10   2021-08-21 11:30:00        Liverpool          Burnley     16386
11   2021-08-21 14:00:00  Manchester City     Norwich City     16387
12   2021-08-21 14:00:00      Aston Villa    Newcastle Utd     16388
13   2021-08-21 14:00:00   Crystal Palace        Brentford     16389
14   2021-08-21 14:00:00     Leeds United          Everton     16390
15   2021-08-21 16:30:00         Brighton          Watford     16391
16   2021-08-22 13:00:00      Southampton   Manchester Utd     16392
17   2021-08-22 13:00:00           Wolves        Tottenham     16393
18   2021-08-22 15:30:00          Arsenal          Chelsea     16394
19   2021-08-23 19:00:00         West Ham   Leicester City     16395
20   2021-08-28 11:30:00  Manchester City          Arsenal     16396
21   2021-08-28 14:00:00    Newcastle Utd      Southampton     16397
22   2021-08-28 14:00:00     Norwich City   Leicester City     16398
23   2021-08-28 14:00:00      Aston Villa        Brentford     16399
24   2021-08-28 14:00:00         Brighton          Everton     16400
25   2021-08-28 14:00:00         West Ham   Crystal Palace     16401
26   2021-08-28 16:30:00        Liverpool          Chelsea     16402
27   2021-08-29 13:00:00          Burnley     Leeds United     16403
28   2021-08-29 13:00:00        Tottenham          Watford     16404
29   2021-08-29 15:30:00           Wolves   Manchester Utd     16405
..                   ...              ...              ...       ...
350  2022-05-08 13:00:00          Arsenal     Leeds United     16735
351  2022-05-08 15:30:00  Manchester City    Newcastle Utd     16727
352  2022-05-10 19:00:00      Aston Villa        Liverpool     16705
353  2022-05-11 18:30:00     Leeds United          Chelsea     16703
354  2022-05-11 18:45:00   Leicester City     Norwich City     16582
355  2022-05-11 18:45:00          Watford          Everton     16674
356  2022-05-11 19:15:00           Wolves  Manchester City     16696
357  2022-05-12 18:45:00        Tottenham          Arsenal     16593
358  2022-05-15 11:00:00        Tottenham          Burnley     16739
359  2022-05-15 13:00:00           Wolves     Norwich City     16736
360  2022-05-15 13:00:00         West Ham  Manchester City     16737
361  2022-05-15 13:00:00          Watford   Leicester City     16738
362  2022-05-15 13:00:00     Leeds United         Brighton     16743
363  2022-05-15 13:00:00      Aston Villa   Crystal Palace     16745
364  2022-05-15 15:30:00          Everton        Brentford     16744
365  2022-05-16 19:00:00    Newcastle Utd          Arsenal     16741
366  2022-05-17 18:45:00      Southampton        Liverpool     16740
367  2022-05-19 18:45:00          Everton   Crystal Palace     16704
368  2022-05-19 19:00:00      Aston Villa          Burnley     16546
369  2022-05-19 19:00:00          Chelsea   Leicester City     16639
370  2022-05-22 15:00:00          Arsenal          Everton     16746
371  2022-05-22 15:00:00        Brentford     Leeds United     16747
372  2022-05-22 15:00:00         Brighton         West Ham     16748
373  2022-05-22 15:00:00          Burnley    Newcastle Utd     16749
374  2022-05-22 15:00:00          Chelsea          Watford     16750
375  2022-05-22 15:00:00   Crystal Palace   Manchester Utd     16751
376  2022-05-22 15

In [113]:
from datetime import datetime, date

us_order['date'] = pd.to_datetime(us_order['date'])
us_order['date'] = us_order['date'].dt.date.astype(str)
#us_order['date'] = us_order['date']
us_order

date        home_team        away_team  match_id
0    2021-08-13        Brentford          Arsenal     16376
1    2021-08-14   Manchester Utd     Leeds United     16377
2    2021-08-14          Burnley         Brighton     16378
3    2021-08-14          Chelsea   Crystal Palace     16379
4    2021-08-14          Everton      Southampton     16380
5    2021-08-14   Leicester City           Wolves     16381
6    2021-08-14          Watford      Aston Villa     16382
7    2021-08-14     Norwich City        Liverpool     16383
8    2021-08-15    Newcastle Utd         West Ham     16384
9    2021-08-15        Tottenham  Manchester City     16385
10   2021-08-21        Liverpool          Burnley     16386
11   2021-08-21  Manchester City     Norwich City     16387
12   2021-08-21      Aston Villa    Newcastle Utd     16388
13   2021-08-21   Crystal Palace        Brentford     16389
14   2021-08-21     Leeds United          Everton     16390
15   2021-08-21         Brighton          Watford     16391
16   2021-08-22      Southampton   Manchester Utd     16392
17   2021-08-22           Wolves        Tottenham     16393
18   2021-08-22          Arsenal          Chelsea     16394
19   2021-08-23         West Ham   Leicester City     16395
20   2021-08-28  Manchester City          Arsenal     16396
21   2021-08-28    Newcastle Utd      Southampton     16397
22   2021-08-28     Norwich City   Leicester City     16398
23   2021-08-28      Aston Villa        Brentford     16399
24   2021-08-28         Brighton          Everton     16400
25   2021-08-28         West Ham   Crystal Palace     16401
26   2021-08-28        Liverpool          Chelsea     16402
27   2021-08-29          Burnley     Leeds United     16403
28   2021-08-29        Tottenham          Watford     16404
29   2021-08-29           Wolves   Manchester Utd     16405
..          ...              ...              ...       ...
350  2022-05-08          Arsenal     Leeds United     16735
351  2022-05-08  Manchester City    Newcastle Utd     16727
352  2022-05-10      Aston Villa        Liverpool     16705
353  2022-05-11     Leeds United          Chelsea     16703
354  2022-05-11   Leicester City     Norwich City     16582
355  2022-05-11          Watford          Everton     16674
356  2022-05-11           Wolves  Manchester City     16696
357  2022-05-12        Tottenham          Arsenal     16593
358  2022-05-15        Tottenham          Burnley     16739
359  2022-05-15           Wolves     Norwich City     16736
360  2022-05-15         West Ham  Manchester City     16737
361  2022-05-15          Watford   Leicester City     16738
362  2022-05-15     Leeds United         Brighton     16743
363  2022-05-15      Aston Villa   Crystal Palace     16745
364  2022-05-15          Everton        Brentford     16744
365  2022-05-16    Newcastle Utd          Arsenal     16741
366  2022-05-17      Southampton        Liverpool     16740
367  2022-05-19          Everton   Crystal Palace     16704
368  2022-05-19      Aston Villa          Burnley     16546
369  2022-05-19          Chelsea   Leicester City     16639
370  2022-05-22          Arsenal          Everton     16746
371  2022-05-22        Brentford     Leeds United     16747
372  2022-05-22         Brighton         West Ham     16748
373  2022-05-22          Burnley    Newcastle Utd     16749
374  2022-05-22          Chelsea          Watford     16750
375  2022-05-22   Crystal Palace   Manchester Utd     16751
376  2022-05-22   Leicester City      Southampton     16752
377  2022-05-22        Liverpool           Wolves     16753
378  2022-05-22  Manchester City      Aston Villa     16754
379  2022-05-22     Norwich City        Tottenham     16755

[380 rows x 4 columns]

In [118]:
l = []
for index, row in us_order.iterrows():
    home = row['home_team']
    date = str(row['date'])
    l.append(fb_order[(fb_order['Squad'] == home) & (fb_order['Home_Away'] == 'Home') 
                      & (fb_order['Date'] == date)]['order'].values.astype(int))
    
l

[array([0]),
 array([1]),
 array([3]),
 array([4]),
 array([6]),
 array([2]),
 array([5]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([12]),
 array([11]),
 array([14]),
 array([13]),
 array([15]),
 array([17]),
 array([16]),
 array([18]),
 array([19]),
 array([20]),
 array([24]),
 array([21]),
 array([23]),
 array([25]),
 array([22]),
 array([26]),
 array([27]),
 array([28]),
 array([29]),
 array([30]),
 array([33]),
 array([32]),
 array([35]),
 array([34]),
 array([36]),
 array([31]),
 array([37]),
 array([38]),
 array([39]),
 array([40]),
 array([41]),
 array([44]),
 array([45]),
 array([43]),
 array([42]),
 array([46]),
 array([48]),
 array([47]),
 array([49]),
 array([51]),
 array([50]),
 array([54]),
 array([55]),
 array([53]),
 array([52]),
 array([56]),
 array([57]),
 array([58]),
 array([59]),
 array([60]),
 array([62]),
 array([63]),
 array([64]),
 array([61]),
 array([65]),
 array([67]),
 array([66]),
 array([68]),
 array([69]),
 array([70]),
 array([74]),
 a

In [119]:
us_order = pd.concat([us_order, pd.DataFrame(l, columns = {'order'})], axis = 1)
us_order

date        home_team        away_team  match_id  order
0    2021-08-13        Brentford          Arsenal     16376      0
1    2021-08-14   Manchester Utd     Leeds United     16377      1
2    2021-08-14          Burnley         Brighton     16378      3
3    2021-08-14          Chelsea   Crystal Palace     16379      4
4    2021-08-14          Everton      Southampton     16380      6
5    2021-08-14   Leicester City           Wolves     16381      2
6    2021-08-14          Watford      Aston Villa     16382      5
7    2021-08-14     Norwich City        Liverpool     16383      7
8    2021-08-15    Newcastle Utd         West Ham     16384      8
9    2021-08-15        Tottenham  Manchester City     16385      9
10   2021-08-21        Liverpool          Burnley     16386     10
11   2021-08-21  Manchester City     Norwich City     16387     12
12   2021-08-21      Aston Villa    Newcastle Utd     16388     11
13   2021-08-21   Crystal Palace        Brentford     16389     14
14   2021-08-21     Leeds United          Everton     16390     13
15   2021-08-21         Brighton          Watford     16391     15
16   2021-08-22      Southampton   Manchester Utd     16392     17
17   2021-08-22           Wolves        Tottenham     16393     16
18   2021-08-22          Arsenal          Chelsea     16394     18
19   2021-08-23         West Ham   Leicester City     16395     19
20   2021-08-28  Manchester City          Arsenal     16396     20
21   2021-08-28    Newcastle Utd      Southampton     16397     24
22   2021-08-28     Norwich City   Leicester City     16398     21
23   2021-08-28      Aston Villa        Brentford     16399     23
24   2021-08-28         Brighton          Everton     16400     25
25   2021-08-28         West Ham   Crystal Palace     16401     22
26   2021-08-28        Liverpool          Chelsea     16402     26
27   2021-08-29          Burnley     Leeds United     16403     27
28   2021-08-29        Tottenham          Watford     16404     28
29   2021-08-29           Wolves   Manchester Utd     16405     29
..          ...              ...              ...       ...    ...
350  2022-05-08          Arsenal     Leeds United     16735    350
351  2022-05-08  Manchester City    Newcastle Utd     16727    351
352  2022-05-10      Aston Villa        Liverpool     16705    352
353  2022-05-11     Leeds United          Chelsea     16703    353
354  2022-05-11   Leicester City     Norwich City     16582    354
355  2022-05-11          Watford          Everton     16674    355
356  2022-05-11           Wolves  Manchester City     16696    356
357  2022-05-12        Tottenham          Arsenal     16593    357
358  2022-05-15        Tottenham          Burnley     16739    358
359  2022-05-15           Wolves     Norwich City     16736    361
360  2022-05-15         West Ham  Manchester City     16737    363
361  2022-05-15          Watford   Leicester City     16738    360
362  2022-05-15     Leeds United         Brighton     16743    359
363  2022-05-15      Aston Villa   Crystal Palace     16745    362
364  2022-05-15          Everton        Brentford     16744    364
365  2022-05-16    Newcastle Utd          Arsenal     16741    365
366  2022-05-17      Southampton        Liverpool     16740    366
367  2022-05-19          Everton   Crystal Palace     16704    367
368  2022-05-19      Aston Villa          Burnley     16546    368
369  2022-05-19          Chelsea   Leicester City     16639    369
370  2022-05-22          Arsenal          Everton     16746    373
371  2022-05-22        Brentford     Leeds United     16747    370
372  2022-05-22         Brighton         West Ham     16748    374
373  2022-05-22          Burnley    Newcastle Utd     16749    378
374  2022-05-22          Chelsea          Watford     16750    379
375  2022-05-22   Crystal Palace   Manchester Utd     16751    372
376  2022-05-22   Leicester City      Southampton     16752    371
377  2022-05-22        Liverpool           Wolves     1675

In [197]:
fb_order = fb_order[['Date', 'Squad', 'Home_Away', 'order']]
fb_order

Date            Squad Home_Away  order
0    2021-08-13        Brentford      Home      0
1    2021-08-13          Arsenal      Away      0
2    2021-08-14   Manchester Utd      Home      1
3    2021-08-14     Leeds United      Away      1
4    2021-08-14   Leicester City      Home      2
5    2021-08-14           Wolves      Away      2
6    2021-08-14          Burnley      Home      3
7    2021-08-14         Brighton      Away      3
8    2021-08-14          Chelsea      Home      4
9    2021-08-14   Crystal Palace      Away      4
10   2021-08-14          Watford      Home      5
11   2021-08-14      Aston Villa      Away      5
12   2021-08-14          Everton      Home      6
13   2021-08-14      Southampton      Away      6
14   2021-08-14     Norwich City      Home      7
15   2021-08-14        Liverpool      Away      7
16   2021-08-15    Newcastle Utd      Home      8
17   2021-08-15         West Ham      Away      8
18   2021-08-15        Tottenham      Home      9
19   2021-08-15  Manchester City      Away      9
20   2021-08-21        Liverpool      Home     10
21   2021-08-21          Burnley      Away     10
22   2021-08-21      Aston Villa      Home     11
23   2021-08-21    Newcastle Utd      Away     11
24   2021-08-21  Manchester City      Home     12
25   2021-08-21     Norwich City      Away     12
26   2021-08-21     Leeds United      Home     13
27   2021-08-21          Everton      Away     13
28   2021-08-21   Crystal Palace      Home     14
29   2021-08-21        Brentford      Away     14
..          ...              ...       ...    ...
730  2022-05-16    Newcastle Utd      Home    365
731  2022-05-16          Arsenal      Away    365
732  2022-05-17      Southampton      Home    366
733  2022-05-17        Liverpool      Away    366
734  2022-05-19          Everton      Home    367
735  2022-05-19   Crystal Palace      Away    367
736  2022-05-19      Aston Villa      Home    368
737  2022-05-19          Burnley      Away    368
738  2022-05-19          Chelsea      Home    369
739  2022-05-19   Leicester City      Away    369
740  2022-05-22        Brentford      Home    370
741  2022-05-22     Leeds United      Away    370
742  2022-05-22   Leicester City      Home    371
743  2022-05-22      Southampton      Away    371
744  2022-05-22   Crystal Palace      Home    372
745  2022-05-22   Manchester Utd      Away    372
746  2022-05-22          Arsenal      Home    373
747  2022-05-22          Everton      Away    373
748  2022-05-22         Brighton      Home    374
749  2022-05-22         West Ham      Away    374
750  2022-05-22     Norwich City      Home    375
751  2022-05-22        Tottenham      Away    375
752  2022-05-22  Manchester City      Home    376
753  2022-05-22      Aston Villa      Away    376
754  2022-05-22        Liverpool      Home    377
755  2022-05-22           Wolves      Away    377
756  2022-05-22          Burnley      Home    378
757  2022-05-22    Newcastle Utd      Away    378
758  2022-05-22          Chelsea      Home    379
759  2022-05-22          Watford      Away    379

[760 rows x 4 columns]

In [120]:
us_order = us_order[['match_id', 'order']]
us_order

match_id  order
0       16376      0
1       16377      1
2       16378      3
3       16379      4
4       16380      6
5       16381      2
6       16382      5
7       16383      7
8       16384      8
9       16385      9
10      16386     10
11      16387     12
12      16388     11
13      16389     14
14      16390     13
15      16391     15
16      16392     17
17      16393     16
18      16394     18
19      16395     19
20      16396     20
21      16397     24
22      16398     21
23      16399     23
24      16400     25
25      16401     22
26      16402     26
27      16403     27
28      16404     28
29      16405     29
..        ...    ...
350     16735    350
351     16727    351
352     16705    352
353     16703    353
354     16582    354
355     16674    355
356     16696    356
357     16593    357
358     16739    358
359     16736    361
360     16737    363
361     16738    360
362     16743    359
363     16745    362
364     16744    364
365     16741    365
366     16740    366
367     16704    367
368     16546    368
369     16639    369
370     16746    373
371     16747    370
372     16748    374
373     16749    378
374     16750    379
375     16751    372
376     16752    371
377     16753    377
378     16754    376
379     16755    375

[380 rows x 2 columns]

### marker for events in extra time of 1st half

In [399]:
fb['45+'] = np.where(fb['Minute'].str.contains('45+'), 1, 0)
fb

Date          Squad Home_Away  Match_Half Minute  \
0     2021-08-13      Brentford      Home           1     11   
1     2021-08-13      Brentford      Home           1     12   
2     2021-08-13      Brentford      Home           1     22   
3     2021-08-13      Brentford      Home           1     28   
4     2021-08-13      Brentford      Home           1     30   
5     2021-08-13      Brentford      Home           2     66   
6     2021-08-13      Brentford      Home           2     73   
7     2021-08-13      Brentford      Home           2     80   
8     2021-08-13        Arsenal      Away           1      2   
9     2021-08-13        Arsenal      Away           1     16   
10    2021-08-13        Arsenal      Away           1     31   
11    2021-08-13        Arsenal      Away           1     33   
12    2021-08-13        Arsenal      Away           1     38   
13    2021-08-13        Arsenal      Away           1     42   
14    2021-08-13        Arsenal      Away           1   45+1   
15    2021-08-13        Arsenal      Away           2     51   
16    2021-08-13        Arsenal      Away           2     60   
17    2021-08-13        Arsenal      Away           2     64   
18    2021-08-13        Arsenal      Away           2     65   
19    2021-08-13        Arsenal      Away           2     68   
20    2021-08-13        Arsenal      Away           2     70   
21    2021-08-13        Arsenal      Away           2     76   
22    2021-08-13        Arsenal      Away           2     77   
23    2021-08-13        Arsenal      Away           2     83   
24    2021-08-13        Arsenal      Away           2     86   
25    2021-08-13        Arsenal      Away           2     87   
26    2021-08-13        Arsenal      Away           2     87   
27    2021-08-13        Arsenal      Away           2   90+1   
28    2021-08-13        Arsenal      Away           2   90+2   
29    2021-08-13        Arsenal      Away           2   90+2   
...          ...            ...       ...         ...    ...   
9754  2022-05-22  Newcastle Utd      Away           2     60   
9755  2022-05-22  Newcastle Utd      Away           2     85   
9756  2022-05-22  Newcastle Utd      Away           2     90   
9757  2022-05-22        Chelsea      Home           1      5   
9758  2022-05-22        Chelsea      Home           1      9   
9759  2022-05-22        Chelsea      Home           1      9   
9760  2022-05-22        Chelsea      Home           1      9   
9761  2022-05-22        Chelsea      Home           1     11   
9762  2022-05-22        Chelsea      Home           1     15   
9763  2022-05-22        Chelsea      Home           1     21   
9764  2022-05-22        Chelsea      Home           1     39   
9765  2022-05-22        Chelsea      Home           1     40   
9766  2022-05-22        Chelsea      Home           1     44   
9767  2022-05-22        Chelsea      Home           1   45+1   
9768  2022-05-22        Chelsea      Home           2     63   
9769  2022-05-22        Chelsea      Home           2     64   
9770  2022-05-22        Chelsea      Home           2     70   
9771  2022-05-22        Chelsea      Home           2     71   
9772  2022-05-22        Chelsea      Home           2     81   
9773  2022-05-22        Chelsea      Home           2     83   
9774  2022-05-22        Chelsea      Home           2   90+1   
9775  2022-05-22        Chelsea      Home           2   90+3   
9776  2022-05-22        Watford      Away           1     14   
9777  2022-05-22        Watford      Away           1     25   
9778  2022-05-22        Watford      Away           1     25   
9779  2022-05-22        Watford      Away           1     31   
9780  2022-05-22        Watford      Away           2     48   
9781  2022-05-22        Watford      Away           2     50   
9782  2022-05-22        Watford      Away           2     80   
9783  2022-05-22        Watford      Away           2     87   

           Shooting_Player     Outcome  Dis

In [400]:
fb['Minute'] = pd.DataFrame(list(eval(s) for s in fb['Minute']))
fb

Date          Squad Home_Away  Match_Half  Minute  \
0     2021-08-13      Brentford      Home           1      11   
1     2021-08-13      Brentford      Home           1      12   
2     2021-08-13      Brentford      Home           1      22   
3     2021-08-13      Brentford      Home           1      28   
4     2021-08-13      Brentford      Home           1      30   
5     2021-08-13      Brentford      Home           2      66   
6     2021-08-13      Brentford      Home           2      73   
7     2021-08-13      Brentford      Home           2      80   
8     2021-08-13        Arsenal      Away           1       2   
9     2021-08-13        Arsenal      Away           1      16   
10    2021-08-13        Arsenal      Away           1      31   
11    2021-08-13        Arsenal      Away           1      33   
12    2021-08-13        Arsenal      Away           1      38   
13    2021-08-13        Arsenal      Away           1      42   
14    2021-08-13        Arsenal      Away           1      46   
15    2021-08-13        Arsenal      Away           2      51   
16    2021-08-13        Arsenal      Away           2      60   
17    2021-08-13        Arsenal      Away           2      64   
18    2021-08-13        Arsenal      Away           2      65   
19    2021-08-13        Arsenal      Away           2      68   
20    2021-08-13        Arsenal      Away           2      70   
21    2021-08-13        Arsenal      Away           2      76   
22    2021-08-13        Arsenal      Away           2      77   
23    2021-08-13        Arsenal      Away           2      83   
24    2021-08-13        Arsenal      Away           2      86   
25    2021-08-13        Arsenal      Away           2      87   
26    2021-08-13        Arsenal      Away           2      87   
27    2021-08-13        Arsenal      Away           2      91   
28    2021-08-13        Arsenal      Away           2      92   
29    2021-08-13        Arsenal      Away           2      92   
...          ...            ...       ...         ...     ...   
9754  2022-05-22  Newcastle Utd      Away           2      60   
9755  2022-05-22  Newcastle Utd      Away           2      85   
9756  2022-05-22  Newcastle Utd      Away           2      90   
9757  2022-05-22        Chelsea      Home           1       5   
9758  2022-05-22        Chelsea      Home           1       9   
9759  2022-05-22        Chelsea      Home           1       9   
9760  2022-05-22        Chelsea      Home           1       9   
9761  2022-05-22        Chelsea      Home           1      11   
9762  2022-05-22        Chelsea      Home           1      15   
9763  2022-05-22        Chelsea      Home           1      21   
9764  2022-05-22        Chelsea      Home           1      39   
9765  2022-05-22        Chelsea      Home           1      40   
9766  2022-05-22        Chelsea      Home           1      44   
9767  2022-05-22        Chelsea      Home           1      46   
9768  2022-05-22        Chelsea      Home           2      63   
9769  2022-05-22        Chelsea      Home           2      64   
9770  2022-05-22        Chelsea      Home           2      70   
9771  2022-05-22        Chelsea      Home           2      71   
9772  2022-05-22        Chelsea      Home           2      81   
9773  2022-05-22        Chelsea      Home           2      83   
9774  2022-05-22        Chelsea      Home           2      91   
9775  2022-05-22        Chelsea      Home           2      93   
9776  2022-05-22        Watford      Away           1      14   
9777  2022-05-22        Watford      Away           1      25   
9778  2022-05-22        Watford      Away           1      25   
9779  2022-05-22        Watford      Away           1      31   
9780  2022-05-22        Watford      Away           2      48   
9781  2022-05-22        Watford      Away           2      50   
9782  2022-05-22        Watford      Away           2      80   
9783  2022-05-22        Watford      Away      

### reorder

In [401]:
fb = fb.drop(columns = ['Home_Away'])
fb = fb.merge(fb_order)
fb = fb.sort_values(['order', 'Minute'])
fb

Date          Squad  Match_Half  Minute       Shooting_Player  \
8     2021-08-13        Arsenal           1       2        Kieran Tierney   
0     2021-08-13      Brentford           1      11          Frank Onyeka   
1     2021-08-13      Brentford           1      12          Bryan Mbeumo   
9     2021-08-13        Arsenal           1      16        Calum Chambers   
2     2021-08-13      Brentford           1      22           Sergi Canós   
3     2021-08-13      Brentford           1      28           Sergi Canós   
4     2021-08-13      Brentford           1      30          Bryan Mbeumo   
10    2021-08-13        Arsenal           1      31       Folarin Balogun   
11    2021-08-13        Arsenal           1      33          Nicolas Pépé   
12    2021-08-13        Arsenal           1      38       Folarin Balogun   
13    2021-08-13        Arsenal           1      42       Folarin Balogun   
14    2021-08-13        Arsenal           1      46          Nicolas Pépé   
15    2021-08-13        Arsenal           2      51      Emile Smith Rowe   
16    2021-08-13        Arsenal           2      60  Albert Sambi Lokonga   
17    2021-08-13        Arsenal           2      64        Kieran Tierney   
18    2021-08-13        Arsenal           2      65            Martinelli   
5     2021-08-13      Brentford           2      66           Sergi Canós   
19    2021-08-13        Arsenal           2      68        Calum Chambers   
20    2021-08-13        Arsenal           2      70          Granit Xhaka   
6     2021-08-13      Brentford           2      73    Christian Nørgaard   
21    2021-08-13        Arsenal           2      76        Kieran Tierney   
22    2021-08-13        Arsenal           2      77          Nicolas Pépé   
7     2021-08-13      Brentford           2      80    Christian Nørgaard   
23    2021-08-13        Arsenal           2      83          Nuno Tavares   
24    2021-08-13        Arsenal           2      86          Granit Xhaka   
25    2021-08-13        Arsenal           2      87          Nicolas Pépé   
26    2021-08-13        Arsenal           2      87            Pablo Marí   
27    2021-08-13        Arsenal           2      91  Albert Sambi Lokonga   
28    2021-08-13        Arsenal           2      92          Reiss Nelson   
29    2021-08-13        Arsenal           2      92      Emile Smith Rowe   
...          ...            ...         ...     ...                   ...   
9755  2022-05-22  Newcastle Utd           2      85         Callum Wilson   
9748  2022-05-22        Burnley           2      88         Maxwel Cornet   
9756  2022-05-22  Newcastle Utd           2      90         Callum Wilson   
9757  2022-05-22        Chelsea           1       5           Kai Havertz   
9758  2022-05-22        Chelsea           1       9                Kenedy   
9759  2022-05-22        Chelsea           1       9           Saúl Ñíguez   
9760  2022-05-22        Chelsea           1       9           Mason Mount   
9761  2022-05-22        Chelsea           1      11           Kai Havertz   
9776  2022-05-22        Watford           1      14        Moussa Sissoko   
9762  2022-05-22        Chelsea           1      15           Saúl Ñíguez   
9763  2022-05-22        Chelsea           1      21           Mason Mount   
9777  2022-05-22        Watford           1      25         Tom Cleverley   
9778  2022-05-22        Watford           1      25           Edo Kayembe   
9779  2022-05-22        Watford           1      31          Kiko Femenía   
9764  2022-05-22        Chelsea           1      39           Mason Mount   
9765  2022-05-22        Chelsea           1      40           Kai Havertz   
9766  2022-05-22        Chelsea           1      44           Mason Mount   
9767  2022-05-22        Chelsea           1      46           Kai Havertz   
9780  2022-05-22        Watford           2      48            João Pedro   
9781  2022-05-22        Watford           2      50              Ken Sema   
9768  20

In [175]:
us = us.merge(us_order)
us = us.sort_values([['order', 'minute']])
us

league      id  minute       result      X      Y        xG  \
8       EPL  425563       1    SavedShot  0.715  0.532  0.017222   
0       EPL  425564      10  MissedShots  0.913  0.539  0.053464   
1       EPL  425565      11   ShotOnPost  0.908  0.315  0.118297   
9       EPL  425566      15  MissedShots  0.847  0.312  0.025566   
2       EPL  425567      21         Goal  0.874  0.698  0.052145   
3       EPL  425568      27  MissedShots  0.812  0.478  0.065706   
4       EPL  425569      29  MissedShots  0.892  0.357  0.080691   
10      EPL  425570      30  MissedShots  0.916  0.515  0.096495   
11      EPL  425571      32  MissedShots  0.819  0.270  0.024410   
12      EPL  425572      37  MissedShots  0.825  0.748  0.019192   
13      EPL  425573      41  MissedShots  0.905  0.518  0.041767   
14      EPL  425574      45  BlockedShot  0.862  0.371  0.051384   
15      EPL  425575      50    SavedShot  0.852  0.550  0.071917   
16      EPL  425576      59    SavedShot  0.748  0.369  0.017827   
17      EPL  425577      63  BlockedShot  0.860  0.666  0.044574   
18      EPL  425578      64  MissedShots  0.966  0.567  0.121241   
5       EPL  425579      65    SavedShot  0.882  0.332  0.072584   
19      EPL  425580      66  BlockedShot  0.812  0.343  0.036226   
20      EPL  425581      69  MissedShots  0.888  0.634  0.055561   
6       EPL  425582      72         Goal  0.969  0.481  0.886598   
21      EPL  425583      75  MissedShots  0.892  0.670  0.091006   
22      EPL  425584      76  MissedShots  0.807  0.767  0.050919   
7       EPL  425585      79  MissedShots  0.973  0.528  0.558696   
23      EPL  425586      82  MissedShots  0.772  0.287  0.014195   
24      EPL  425587      85  MissedShots  0.748  0.429  0.018808   
25      EPL  425588      86    SavedShot  0.865  0.599  0.085683   
26      EPL  425589      86  MissedShots  0.953  0.409  0.031568   
27      EPL  425590      90  MissedShots  0.706  0.549  0.010266   
28      EPL  425591      91  BlockedShot  0.837  0.463  0.037434   
29      EPL  425592      91  MissedShots  0.875  0.342  0.060589   
...     ...     ...     ...          ...    ...    ...       ...   
9618    EPL  477799      84    SavedShot  0.813  0.351  0.049672   
9611    EPL  477800      87    SavedShot  0.916  0.467  0.093559   
9619    EPL  477801      89  MissedShots  0.817  0.779  0.019961   
9620    EPL  477802       4    SavedShot  0.924  0.668  0.342955   
9621    EPL  477803       8  BlockedShot  0.868  0.677  0.053565   
9622    EPL  477804       8  BlockedShot  0.717  0.519  0.012197   
9623    EPL  477805       8  MissedShots  0.880  0.499  0.101134   
9624    EPL  477806      10         Goal  0.952  0.478  0.660082   
9639    EPL  477807      13  BlockedShot  0.815  0.445  0.049920   
9625    EPL  477808      14  MissedShots  0.759  0.612  0.025008   
9626    EPL  477809      20  MissedShots  0.959  0.598  0.230541   
9640    EPL  477810      24  BlockedShot  0.806  0.651  0.025188   
9641    EPL  477811      24  MissedShots  0.821  0.371  0.057461   
9642    EPL  477812      30    SavedShot  0.889  0.298  0.031365   
9627    EPL  477813      38    SavedShot  0.899  0.306  0.065632   
9628    EPL  477814      39  BlockedShot  0.917  0.588  0.132610   
9629    EPL  477815      43  BlockedShot  0.864  0.437  0.109327   
9630    EPL  477816      45   ShotOnPost  0.962  0.656  0.088153   
9643    EPL  477817      47    SavedShot  0.878  0.520  0.147609   
9644    EPL  477818      50  BlockedShot  0.811  0.696  0.075678   
9631    EPL  477819      62  BlockedShot  0.741  0.575  0.026353   
9632    EPL  477820      63    SavedShot  0.811  0.299  0.033596   
9633    EPL  477821      69    SavedShot  0.749  0.648  0.024635   
9634    EPL  477822      70  MissedShots  0.844  0.612  0.021016   
9645    EPL  477823      79  MissedShots  0.566  0.325  0.007345   
9635    EPL  477824      80    SavedShot  0.783  0.596  0.040275   
9636    EPL  477825      82  MissedShots  0.942  0.675  0.081

### find diff. 9 obs.

In [407]:
agg_fb = fb.groupby(['order'])['Date'].count()
agg_fb

order
0      30
1      26
2      26
3      28
4      17
5      24
6      20
7      33
8      35
9      31
10     36
11     19
12     17
13     34
14     21
15     23
16     33
17     23
18     28
19     24
20     26
21     23
22     23
23     16
24     32
25     28
26     29
27     24
28     24
29     25
       ..
350    22
351    28
352    26
353    22
354    29
355    22
356    22
357    24
358    29
359    34
360    26
361    28
362    29
363    37
364    28
365    27
366    28
367    19
368    32
369    22
370    28
371    19
372    16
373    32
374    25
375    28
376    28
377    36
378    20
379    27
Name: Date, Length: 380, dtype: int64

In [369]:
agg_us = us.groupby(['order'])['id'].count()
agg_us

order
0      30
1      26
2      26
3      28
4      17
5      24
6      20
7      33
8      35
9      31
10     36
11     19
12     17
13     34
14     21
15     23
16     33
17     23
18     28
19     24
20     26
21     23
22     23
23     16
24     32
25     28
26     29
27     24
28     24
29     25
       ..
350    22
351    28
352    26
353    22
354    29
355    22
356    22
357    24
358    29
359    34
360    26
361    28
362    29
363    37
364    28
365    27
366    28
367    19
368    32
369    22
370    28
371    19
372    16
373    32
374    25
375    28
376    28
377    36
378    20
379    27
Name: id, Length: 380, dtype: int64

In [408]:
count = 0
c = 0
uf = []
fu = []
for i in range(380):
    if agg_fb[i] != agg_us[i]:
        if agg_us[i] > agg_fb[i]:
            uf.append((i, agg_fb[i], agg_us[i]))
        else:
            fu.append((i, agg_fb[i], agg_us[i]))
        

In [394]:
uf = pd.DataFrame(uf)
uf

Empty DataFrame
Columns: []
Index: []

In [409]:
fu

[]

In [270]:
len(us[us['result'] == 'OwnGoal'])

0

### remove ownGoal

In [262]:
us = us[us['result'] != 'OwnGoal']
us

league      id  minute       result      X      Y        xG  \
8       EPL  425563       1    SavedShot  0.715  0.532  0.017222   
0       EPL  425564      10  MissedShots  0.913  0.539  0.053464   
1       EPL  425565      11   ShotOnPost  0.908  0.315  0.118297   
9       EPL  425566      15  MissedShots  0.847  0.312  0.025566   
2       EPL  425567      21         Goal  0.874  0.698  0.052145   
3       EPL  425568      27  MissedShots  0.812  0.478  0.065706   
4       EPL  425569      29  MissedShots  0.892  0.357  0.080691   
10      EPL  425570      30  MissedShots  0.916  0.515  0.096495   
11      EPL  425571      32  MissedShots  0.819  0.270  0.024410   
12      EPL  425572      37  MissedShots  0.825  0.748  0.019192   
13      EPL  425573      41  MissedShots  0.905  0.518  0.041767   
14      EPL  425574      45  BlockedShot  0.862  0.371  0.051384   
15      EPL  425575      50    SavedShot  0.852  0.550  0.071917   
16      EPL  425576      59    SavedShot  0.748  0.369  0.017827   
17      EPL  425577      63  BlockedShot  0.860  0.666  0.044574   
18      EPL  425578      64  MissedShots  0.966  0.567  0.121241   
5       EPL  425579      65    SavedShot  0.882  0.332  0.072584   
19      EPL  425580      66  BlockedShot  0.812  0.343  0.036226   
20      EPL  425581      69  MissedShots  0.888  0.634  0.055561   
6       EPL  425582      72         Goal  0.969  0.481  0.886598   
21      EPL  425583      75  MissedShots  0.892  0.670  0.091006   
22      EPL  425584      76  MissedShots  0.807  0.767  0.050919   
7       EPL  425585      79  MissedShots  0.973  0.528  0.558696   
23      EPL  425586      82  MissedShots  0.772  0.287  0.014195   
24      EPL  425587      85  MissedShots  0.748  0.429  0.018808   
25      EPL  425588      86    SavedShot  0.865  0.599  0.085683   
26      EPL  425589      86  MissedShots  0.953  0.409  0.031568   
27      EPL  425590      90  MissedShots  0.706  0.549  0.010266   
28      EPL  425591      91  BlockedShot  0.837  0.463  0.037434   
29      EPL  425592      91  MissedShots  0.875  0.342  0.060589   
...     ...     ...     ...          ...    ...    ...       ...   
9618    EPL  477799      84    SavedShot  0.813  0.351  0.049672   
9611    EPL  477800      87    SavedShot  0.916  0.467  0.093559   
9619    EPL  477801      89  MissedShots  0.817  0.779  0.019961   
9620    EPL  477802       4    SavedShot  0.924  0.668  0.342955   
9621    EPL  477803       8  BlockedShot  0.868  0.677  0.053565   
9622    EPL  477804       8  BlockedShot  0.717  0.519  0.012197   
9623    EPL  477805       8  MissedShots  0.880  0.499  0.101134   
9624    EPL  477806      10         Goal  0.952  0.478  0.660082   
9639    EPL  477807      13  BlockedShot  0.815  0.445  0.049920   
9625    EPL  477808      14  MissedShots  0.759  0.612  0.025008   
9626    EPL  477809      20  MissedShots  0.959  0.598  0.230541   
9640    EPL  477810      24  BlockedShot  0.806  0.651  0.025188   
9641    EPL  477811      24  MissedShots  0.821  0.371  0.057461   
9642    EPL  477812      30    SavedShot  0.889  0.298  0.031365   
9627    EPL  477813      38    SavedShot  0.899  0.306  0.065632   
9628    EPL  477814      39  BlockedShot  0.917  0.588  0.132610   
9629    EPL  477815      43  BlockedShot  0.864  0.437  0.109327   
9630    EPL  477816      45   ShotOnPost  0.962  0.656  0.088153   
9643    EPL  477817      47    SavedShot  0.878  0.520  0.147609   
9644    EPL  477818      50  BlockedShot  0.811  0.696  0.075678   
9631    EPL  477819      62  BlockedShot  0.741  0.575  0.026353   
9632    EPL  477820      63    SavedShot  0.811  0.299  0.033596   
9633    EPL  477821      69    SavedShot  0.749  0.648  0.024635   
9634    EPL  477822      70  MissedShots  0.844  0.612  0.021016   
9645    EPL  477823      79  MissedShots  0.566  0.325  0.007345   
9635    EPL  477824      80    SavedShot  0.783  0.596  0.040275   
9636    EPL  477825      82  MissedShots  0.942  0.675  0.081

### fix time diff. in US

In [263]:
us['minute'] = us['minute'] + 1
us

C:\Users\ad\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


league      id  minute       result      X      Y        xG  \
8       EPL  425563       2    SavedShot  0.715  0.532  0.017222   
0       EPL  425564      11  MissedShots  0.913  0.539  0.053464   
1       EPL  425565      12   ShotOnPost  0.908  0.315  0.118297   
9       EPL  425566      16  MissedShots  0.847  0.312  0.025566   
2       EPL  425567      22         Goal  0.874  0.698  0.052145   
3       EPL  425568      28  MissedShots  0.812  0.478  0.065706   
4       EPL  425569      30  MissedShots  0.892  0.357  0.080691   
10      EPL  425570      31  MissedShots  0.916  0.515  0.096495   
11      EPL  425571      33  MissedShots  0.819  0.270  0.024410   
12      EPL  425572      38  MissedShots  0.825  0.748  0.019192   
13      EPL  425573      42  MissedShots  0.905  0.518  0.041767   
14      EPL  425574      46  BlockedShot  0.862  0.371  0.051384   
15      EPL  425575      51    SavedShot  0.852  0.550  0.071917   
16      EPL  425576      60    SavedShot  0.748  0.369  0.017827   
17      EPL  425577      64  BlockedShot  0.860  0.666  0.044574   
18      EPL  425578      65  MissedShots  0.966  0.567  0.121241   
5       EPL  425579      66    SavedShot  0.882  0.332  0.072584   
19      EPL  425580      67  BlockedShot  0.812  0.343  0.036226   
20      EPL  425581      70  MissedShots  0.888  0.634  0.055561   
6       EPL  425582      73         Goal  0.969  0.481  0.886598   
21      EPL  425583      76  MissedShots  0.892  0.670  0.091006   
22      EPL  425584      77  MissedShots  0.807  0.767  0.050919   
7       EPL  425585      80  MissedShots  0.973  0.528  0.558696   
23      EPL  425586      83  MissedShots  0.772  0.287  0.014195   
24      EPL  425587      86  MissedShots  0.748  0.429  0.018808   
25      EPL  425588      87    SavedShot  0.865  0.599  0.085683   
26      EPL  425589      87  MissedShots  0.953  0.409  0.031568   
27      EPL  425590      91  MissedShots  0.706  0.549  0.010266   
28      EPL  425591      92  BlockedShot  0.837  0.463  0.037434   
29      EPL  425592      92  MissedShots  0.875  0.342  0.060589   
...     ...     ...     ...          ...    ...    ...       ...   
9618    EPL  477799      85    SavedShot  0.813  0.351  0.049672   
9611    EPL  477800      88    SavedShot  0.916  0.467  0.093559   
9619    EPL  477801      90  MissedShots  0.817  0.779  0.019961   
9620    EPL  477802       5    SavedShot  0.924  0.668  0.342955   
9621    EPL  477803       9  BlockedShot  0.868  0.677  0.053565   
9622    EPL  477804       9  BlockedShot  0.717  0.519  0.012197   
9623    EPL  477805       9  MissedShots  0.880  0.499  0.101134   
9624    EPL  477806      11         Goal  0.952  0.478  0.660082   
9639    EPL  477807      14  BlockedShot  0.815  0.445  0.049920   
9625    EPL  477808      15  MissedShots  0.759  0.612  0.025008   
9626    EPL  477809      21  MissedShots  0.959  0.598  0.230541   
9640    EPL  477810      25  BlockedShot  0.806  0.651  0.025188   
9641    EPL  477811      25  MissedShots  0.821  0.371  0.057461   
9642    EPL  477812      31    SavedShot  0.889  0.298  0.031365   
9627    EPL  477813      39    SavedShot  0.899  0.306  0.065632   
9628    EPL  477814      40  BlockedShot  0.917  0.588  0.132610   
9629    EPL  477815      44  BlockedShot  0.864  0.437  0.109327   
9630    EPL  477816      46   ShotOnPost  0.962  0.656  0.088153   
9643    EPL  477817      48    SavedShot  0.878  0.520  0.147609   
9644    EPL  477818      51  BlockedShot  0.811  0.696  0.075678   
9631    EPL  477819      63  BlockedShot  0.741  0.575  0.026353   
9632    EPL  477820      64    SavedShot  0.811  0.299  0.033596   
9633    EPL  477821      70    SavedShot  0.749  0.648  0.024635   
9634    EPL  477822      71  MissedShots  0.844  0.612  0.021016   
9645    EPL  477823      80  MissedShots  0.566  0.325  0.007345   
9635    EPL  477824      81    SavedShot  0.783  0.596  0.040275   
9636    EPL  477825      83  MissedShots  0.942  0.675  0.081

### fix uf

In [300]:
del_id = []
for index, row in uf.iterrows():
    order = row[0]
    fb_match = fb[fb['order'] == order]
    us_match = us[us['order'] == order]
    
    flag = False
    for i in range(len(fb_match)):
        if us_match.iloc[i]['minute'] != fb_match.iloc[i]['Minute']:
            del_id.append(us_match.iloc[i]['id'])
            flag = True
            break
    
    if(flag == False):
        del_id.append(us_match.iloc[len(fb_match)]['id'])
        flag = True
      
    
    
del_id

[431114,
 433458,
 433694,
 434918,
 442601,
 448897,
 450751,
 450778,
 454968,
 462982,
 468712,
 475292,
 476511,
 477960]

In [301]:
len(del_id)

14

In [379]:
us = us[~(us['id'].isin(del_id))]
us

league      id  minute       result      X      Y        xG  \
8       EPL  425563       2    SavedShot  0.715  0.532  0.017222   
0       EPL  425564      11  MissedShots  0.913  0.539  0.053464   
1       EPL  425565      12   ShotOnPost  0.908  0.315  0.118297   
9       EPL  425566      16  MissedShots  0.847  0.312  0.025566   
2       EPL  425567      22         Goal  0.874  0.698  0.052145   
3       EPL  425568      28  MissedShots  0.812  0.478  0.065706   
4       EPL  425569      30  MissedShots  0.892  0.357  0.080691   
10      EPL  425570      31  MissedShots  0.916  0.515  0.096495   
11      EPL  425571      33  MissedShots  0.819  0.270  0.024410   
12      EPL  425572      38  MissedShots  0.825  0.748  0.019192   
13      EPL  425573      42  MissedShots  0.905  0.518  0.041767   
14      EPL  425574      46  BlockedShot  0.862  0.371  0.051384   
15      EPL  425575      51    SavedShot  0.852  0.550  0.071917   
16      EPL  425576      60    SavedShot  0.748  0.369  0.017827   
17      EPL  425577      64  BlockedShot  0.860  0.666  0.044574   
18      EPL  425578      65  MissedShots  0.966  0.567  0.121241   
5       EPL  425579      66    SavedShot  0.882  0.332  0.072584   
19      EPL  425580      67  BlockedShot  0.812  0.343  0.036226   
20      EPL  425581      70  MissedShots  0.888  0.634  0.055561   
6       EPL  425582      73         Goal  0.969  0.481  0.886598   
21      EPL  425583      76  MissedShots  0.892  0.670  0.091006   
22      EPL  425584      77  MissedShots  0.807  0.767  0.050919   
7       EPL  425585      80  MissedShots  0.973  0.528  0.558696   
23      EPL  425586      83  MissedShots  0.772  0.287  0.014195   
24      EPL  425587      86  MissedShots  0.748  0.429  0.018808   
25      EPL  425588      87    SavedShot  0.865  0.599  0.085683   
26      EPL  425589      87  MissedShots  0.953  0.409  0.031568   
27      EPL  425590      91  MissedShots  0.706  0.549  0.010266   
28      EPL  425591      92  BlockedShot  0.837  0.463  0.037434   
29      EPL  425592      92  MissedShots  0.875  0.342  0.060589   
...     ...     ...     ...          ...    ...    ...       ...   
9618    EPL  477799      85    SavedShot  0.813  0.351  0.049672   
9611    EPL  477800      88    SavedShot  0.916  0.467  0.093559   
9619    EPL  477801      90  MissedShots  0.817  0.779  0.019961   
9620    EPL  477802       5    SavedShot  0.924  0.668  0.342955   
9621    EPL  477803       9  BlockedShot  0.868  0.677  0.053565   
9622    EPL  477804       9  BlockedShot  0.717  0.519  0.012197   
9623    EPL  477805       9  MissedShots  0.880  0.499  0.101134   
9624    EPL  477806      11         Goal  0.952  0.478  0.660082   
9639    EPL  477807      14  BlockedShot  0.815  0.445  0.049920   
9625    EPL  477808      15  MissedShots  0.759  0.612  0.025008   
9626    EPL  477809      21  MissedShots  0.959  0.598  0.230541   
9640    EPL  477810      25  BlockedShot  0.806  0.651  0.025188   
9641    EPL  477811      25  MissedShots  0.821  0.371  0.057461   
9642    EPL  477812      31    SavedShot  0.889  0.298  0.031365   
9627    EPL  477813      39    SavedShot  0.899  0.306  0.065632   
9628    EPL  477814      40  BlockedShot  0.917  0.588  0.132610   
9629    EPL  477815      44  BlockedShot  0.864  0.437  0.109327   
9630    EPL  477816      46   ShotOnPost  0.962  0.656  0.088153   
9643    EPL  477817      48    SavedShot  0.878  0.520  0.147609   
9644    EPL  477818      51  BlockedShot  0.811  0.696  0.075678   
9631    EPL  477819      63  BlockedShot  0.741  0.575  0.026353   
9632    EPL  477820      64    SavedShot  0.811  0.299  0.033596   
9633    EPL  477821      70    SavedShot  0.749  0.648  0.024635   
9634    EPL  477822      71  MissedShots  0.844  0.612  0.021016   
9645    EPL  477823      80  MissedShots  0.566  0.325  0.007345   
9635    EPL  477824      81    SavedShot  0.783  0.596  0.040275   
9636    EPL  477825      83  MissedShots  0.942  0.675  0.081

### fix fu

In [405]:
fu = pd.DataFrame(fu)
fu[3] = fu[1] - fu[2]
fu

0   1   2  3
0     7  34  33  1
1     9  32  31  1
2    10  37  36  1
3    13  35  34  1
4    26  30  29  1
5    27  25  24  1
6    44  25  24  1
7    48  28  26  2
8    49  29  28  1
9    54  36  35  1
10   61  16  15  1
11   66  31  30  1
12   68  32  31  1
13   72  23  22  1
14   83  22  20  2
15   92  24  23  1
16  104  18  17  1
17  118  22  21  1
18  126  35  34  1
19  127  25  24  1
20  132  24  23  1
21  145  28  27  1
22  146  25  24  1
23  148  21  20  1
24  151  26  24  2
25  168  29  28  1
26  174  32  31  1
27  193  23  22  1
28  195  26  25  1
29  199  34  33  1
30  202  41  40  1
31  218  32  31  1
32  221  29  28  1
33  224  26  25  1
34  231  29  28  1
35  238  36  35  1
36  240  17  16  1
37  248  37  35  2
38  249  35  34  1
39  262  27  25  2
40  267  21  19  2
41  268  23  22  1
42  273  21  20  1
43  286  28  27  1
44  305  21  20  1
45  325  25  24  1
46  335  31  30  1
47  344  34  33  1
48  347  31  30  1
49  360  27  26  1
50  378  21  20  1

In [356]:
fu[3].sum()

57

In [357]:
del_index = []
for index, row in fu.iterrows():
    order = row[0]
    fb_match = fb[fb['order'] == order]
    us_match = us[us['order'] == order]
    diff = row[1] - row[2]
    index_match = fb_match.index.tolist()
    
    count = 0
    for i in range(len(us_match)):
        if us_match.iloc[i - count]['minute'] != fb_match.iloc[i]['Minute']:
            del_index.append(index_match[i])
            count += 1
            if count == diff:
                break
         
    
    if(count < diff):
        for j in range(1, diff - count + 1):
            del_index.append(index_match[-j])
            count += 1
      
    
    
del_index

[173,
 247,
 284,
 345,
 688,
 731,
 1194,
 1310,
 1315,
 1325,
 1468,
 1644,
 1785,
 1838,
 1945,
 2208,
 2211,
 2464,
 2760,
 3097,
 3278,
 3333,
 3455,
 3802,
 3808,
 3860,
 3933,
 3940,
 4355,
 4492,
 5006,
 5046,
 5152,
 5239,
 5657,
 5733,
 5821,
 5984,
 6177,
 6216,
 6426,
 6432,
 6450,
 6790,
 6793,
 6919,
 6934,
 6943,
 7047,
 7357,
 7835,
 8345,
 8618,
 8836,
 8934,
 9269,
 9744]

In [358]:
len(del_index)

57

In [406]:
fb = fb.drop(del_index)
fb

Date          Squad  Match_Half  Minute       Shooting_Player  \
8     2021-08-13        Arsenal           1       2        Kieran Tierney   
0     2021-08-13      Brentford           1      11          Frank Onyeka   
1     2021-08-13      Brentford           1      12          Bryan Mbeumo   
9     2021-08-13        Arsenal           1      16        Calum Chambers   
2     2021-08-13      Brentford           1      22           Sergi Canós   
3     2021-08-13      Brentford           1      28           Sergi Canós   
4     2021-08-13      Brentford           1      30          Bryan Mbeumo   
10    2021-08-13        Arsenal           1      31       Folarin Balogun   
11    2021-08-13        Arsenal           1      33          Nicolas Pépé   
12    2021-08-13        Arsenal           1      38       Folarin Balogun   
13    2021-08-13        Arsenal           1      42       Folarin Balogun   
14    2021-08-13        Arsenal           1      46          Nicolas Pépé   
15    2021-08-13        Arsenal           2      51      Emile Smith Rowe   
16    2021-08-13        Arsenal           2      60  Albert Sambi Lokonga   
17    2021-08-13        Arsenal           2      64        Kieran Tierney   
18    2021-08-13        Arsenal           2      65            Martinelli   
5     2021-08-13      Brentford           2      66           Sergi Canós   
19    2021-08-13        Arsenal           2      68        Calum Chambers   
20    2021-08-13        Arsenal           2      70          Granit Xhaka   
6     2021-08-13      Brentford           2      73    Christian Nørgaard   
21    2021-08-13        Arsenal           2      76        Kieran Tierney   
22    2021-08-13        Arsenal           2      77          Nicolas Pépé   
7     2021-08-13      Brentford           2      80    Christian Nørgaard   
23    2021-08-13        Arsenal           2      83          Nuno Tavares   
24    2021-08-13        Arsenal           2      86          Granit Xhaka   
25    2021-08-13        Arsenal           2      87          Nicolas Pépé   
26    2021-08-13        Arsenal           2      87            Pablo Marí   
27    2021-08-13        Arsenal           2      91  Albert Sambi Lokonga   
28    2021-08-13        Arsenal           2      92          Reiss Nelson   
29    2021-08-13        Arsenal           2      92      Emile Smith Rowe   
...          ...            ...         ...     ...                   ...   
9755  2022-05-22  Newcastle Utd           2      85         Callum Wilson   
9748  2022-05-22        Burnley           2      88         Maxwel Cornet   
9756  2022-05-22  Newcastle Utd           2      90         Callum Wilson   
9757  2022-05-22        Chelsea           1       5           Kai Havertz   
9758  2022-05-22        Chelsea           1       9                Kenedy   
9759  2022-05-22        Chelsea           1       9           Saúl Ñíguez   
9760  2022-05-22        Chelsea           1       9           Mason Mount   
9761  2022-05-22        Chelsea           1      11           Kai Havertz   
9776  2022-05-22        Watford           1      14        Moussa Sissoko   
9762  2022-05-22        Chelsea           1      15           Saúl Ñíguez   
9763  2022-05-22        Chelsea           1      21           Mason Mount   
9777  2022-05-22        Watford           1      25         Tom Cleverley   
9778  2022-05-22        Watford           1      25           Edo Kayembe   
9779  2022-05-22        Watford           1      31          Kiko Femenía   
9764  2022-05-22        Chelsea           1      39           Mason Mount   
9765  2022-05-22        Chelsea           1      40           Kai Havertz   
9766  2022-05-22        Chelsea           1      44           Mason Mount   
9767  2022-05-22        Chelsea           1      46           Kai Havertz   
9780  2022-05-22        Watford           2      48            João Pedro   
9781  2022-05-22        Watford           2      50              Ken Sema   
9768  20

### join two dfs

In [411]:
us = us.reset_index(drop = True)
us

league      id  minute       result      X      Y        xG  \
0       EPL  425563       2    SavedShot  0.715  0.532  0.017222   
1       EPL  425564      11  MissedShots  0.913  0.539  0.053464   
2       EPL  425565      12   ShotOnPost  0.908  0.315  0.118297   
3       EPL  425566      16  MissedShots  0.847  0.312  0.025566   
4       EPL  425567      22         Goal  0.874  0.698  0.052145   
5       EPL  425568      28  MissedShots  0.812  0.478  0.065706   
6       EPL  425569      30  MissedShots  0.892  0.357  0.080691   
7       EPL  425570      31  MissedShots  0.916  0.515  0.096495   
8       EPL  425571      33  MissedShots  0.819  0.270  0.024410   
9       EPL  425572      38  MissedShots  0.825  0.748  0.019192   
10      EPL  425573      42  MissedShots  0.905  0.518  0.041767   
11      EPL  425574      46  BlockedShot  0.862  0.371  0.051384   
12      EPL  425575      51    SavedShot  0.852  0.550  0.071917   
13      EPL  425576      60    SavedShot  0.748  0.369  0.017827   
14      EPL  425577      64  BlockedShot  0.860  0.666  0.044574   
15      EPL  425578      65  MissedShots  0.966  0.567  0.121241   
16      EPL  425579      66    SavedShot  0.882  0.332  0.072584   
17      EPL  425580      67  BlockedShot  0.812  0.343  0.036226   
18      EPL  425581      70  MissedShots  0.888  0.634  0.055561   
19      EPL  425582      73         Goal  0.969  0.481  0.886598   
20      EPL  425583      76  MissedShots  0.892  0.670  0.091006   
21      EPL  425584      77  MissedShots  0.807  0.767  0.050919   
22      EPL  425585      80  MissedShots  0.973  0.528  0.558696   
23      EPL  425586      83  MissedShots  0.772  0.287  0.014195   
24      EPL  425587      86  MissedShots  0.748  0.429  0.018808   
25      EPL  425588      87    SavedShot  0.865  0.599  0.085683   
26      EPL  425589      87  MissedShots  0.953  0.409  0.031568   
27      EPL  425590      91  MissedShots  0.706  0.549  0.010266   
28      EPL  425591      92  BlockedShot  0.837  0.463  0.037434   
29      EPL  425592      92  MissedShots  0.875  0.342  0.060589   
...     ...     ...     ...          ...    ...    ...       ...   
9697    EPL  477799      85    SavedShot  0.813  0.351  0.049672   
9698    EPL  477800      88    SavedShot  0.916  0.467  0.093559   
9699    EPL  477801      90  MissedShots  0.817  0.779  0.019961   
9700    EPL  477802       5    SavedShot  0.924  0.668  0.342955   
9701    EPL  477803       9  BlockedShot  0.868  0.677  0.053565   
9702    EPL  477804       9  BlockedShot  0.717  0.519  0.012197   
9703    EPL  477805       9  MissedShots  0.880  0.499  0.101134   
9704    EPL  477806      11         Goal  0.952  0.478  0.660082   
9705    EPL  477807      14  BlockedShot  0.815  0.445  0.049920   
9706    EPL  477808      15  MissedShots  0.759  0.612  0.025008   
9707    EPL  477809      21  MissedShots  0.959  0.598  0.230541   
9708    EPL  477810      25  BlockedShot  0.806  0.651  0.025188   
9709    EPL  477811      25  MissedShots  0.821  0.371  0.057461   
9710    EPL  477812      31    SavedShot  0.889  0.298  0.031365   
9711    EPL  477813      39    SavedShot  0.899  0.306  0.065632   
9712    EPL  477814      40  BlockedShot  0.917  0.588  0.132610   
9713    EPL  477815      44  BlockedShot  0.864  0.437  0.109327   
9714    EPL  477816      46   ShotOnPost  0.962  0.656  0.088153   
9715    EPL  477817      48    SavedShot  0.878  0.520  0.147609   
9716    EPL  477818      51  BlockedShot  0.811  0.696  0.075678   
9717    EPL  477819      63  BlockedShot  0.741  0.575  0.026353   
9718    EPL  477820      64    SavedShot  0.811  0.299  0.033596   
9719    EPL  477821      70    SavedShot  0.749  0.648  0.024635   
9720    EPL  477822      71  MissedShots  0.844  0.612  0.021016   
9721    EPL  477823      80  MissedShots  0.566  0.325  0.007345   
9722    EPL  477824      81    SavedShot  0.783  0.596  0.040275   
9723    EPL  477825      83  MissedShots  0.942  0.675  0.081

In [412]:
fb = fb.reset_index(drop = True)
fb

Date          Squad  Match_Half  Minute       Shooting_Player  \
0     2021-08-13        Arsenal           1       2        Kieran Tierney   
1     2021-08-13      Brentford           1      11          Frank Onyeka   
2     2021-08-13      Brentford           1      12          Bryan Mbeumo   
3     2021-08-13        Arsenal           1      16        Calum Chambers   
4     2021-08-13      Brentford           1      22           Sergi Canós   
5     2021-08-13      Brentford           1      28           Sergi Canós   
6     2021-08-13      Brentford           1      30          Bryan Mbeumo   
7     2021-08-13        Arsenal           1      31       Folarin Balogun   
8     2021-08-13        Arsenal           1      33          Nicolas Pépé   
9     2021-08-13        Arsenal           1      38       Folarin Balogun   
10    2021-08-13        Arsenal           1      42       Folarin Balogun   
11    2021-08-13        Arsenal           1      46          Nicolas Pépé   
12    2021-08-13        Arsenal           2      51      Emile Smith Rowe   
13    2021-08-13        Arsenal           2      60  Albert Sambi Lokonga   
14    2021-08-13        Arsenal           2      64        Kieran Tierney   
15    2021-08-13        Arsenal           2      65            Martinelli   
16    2021-08-13      Brentford           2      66           Sergi Canós   
17    2021-08-13        Arsenal           2      68        Calum Chambers   
18    2021-08-13        Arsenal           2      70          Granit Xhaka   
19    2021-08-13      Brentford           2      73    Christian Nørgaard   
20    2021-08-13        Arsenal           2      76        Kieran Tierney   
21    2021-08-13        Arsenal           2      77          Nicolas Pépé   
22    2021-08-13      Brentford           2      80    Christian Nørgaard   
23    2021-08-13        Arsenal           2      83          Nuno Tavares   
24    2021-08-13        Arsenal           2      86          Granit Xhaka   
25    2021-08-13        Arsenal           2      87          Nicolas Pépé   
26    2021-08-13        Arsenal           2      87            Pablo Marí   
27    2021-08-13        Arsenal           2      91  Albert Sambi Lokonga   
28    2021-08-13        Arsenal           2      92          Reiss Nelson   
29    2021-08-13        Arsenal           2      92      Emile Smith Rowe   
...          ...            ...         ...     ...                   ...   
9697  2022-05-22  Newcastle Utd           2      85         Callum Wilson   
9698  2022-05-22        Burnley           2      88         Maxwel Cornet   
9699  2022-05-22  Newcastle Utd           2      90         Callum Wilson   
9700  2022-05-22        Chelsea           1       5           Kai Havertz   
9701  2022-05-22        Chelsea           1       9                Kenedy   
9702  2022-05-22        Chelsea           1       9           Saúl Ñíguez   
9703  2022-05-22        Chelsea           1       9           Mason Mount   
9704  2022-05-22        Chelsea           1      11           Kai Havertz   
9705  2022-05-22        Watford           1      14        Moussa Sissoko   
9706  2022-05-22        Chelsea           1      15           Saúl Ñíguez   
9707  2022-05-22        Chelsea           1      21           Mason Mount   
9708  2022-05-22        Watford           1      25         Tom Cleverley   
9709  2022-05-22        Watford           1      25           Edo Kayembe   
9710  2022-05-22        Watford           1      31          Kiko Femenía   
9711  2022-05-22        Chelsea           1      39           Mason Mount   
9712  2022-05-22        Chelsea           1      40           Kai Havertz   
9713  2022-05-22        Chelsea           1      44           Mason Mount   
9714  2022-05-22        Chelsea           1      46           Kai Havertz   
9715  2022-05-22        Watford           2      48            João Pedro   
9716  2022-05-22        Watford           2      50              Ken Sema   
9717  20

In [415]:
fb = pd.concat([fb, us['xG']], axis = 1)
fb

Date          Squad  Match_Half  Minute       Shooting_Player  \
0     2021-08-13        Arsenal           1       2        Kieran Tierney   
1     2021-08-13      Brentford           1      11          Frank Onyeka   
2     2021-08-13      Brentford           1      12          Bryan Mbeumo   
3     2021-08-13        Arsenal           1      16        Calum Chambers   
4     2021-08-13      Brentford           1      22           Sergi Canós   
5     2021-08-13      Brentford           1      28           Sergi Canós   
6     2021-08-13      Brentford           1      30          Bryan Mbeumo   
7     2021-08-13        Arsenal           1      31       Folarin Balogun   
8     2021-08-13        Arsenal           1      33          Nicolas Pépé   
9     2021-08-13        Arsenal           1      38       Folarin Balogun   
10    2021-08-13        Arsenal           1      42       Folarin Balogun   
11    2021-08-13        Arsenal           1      46          Nicolas Pépé   
12    2021-08-13        Arsenal           2      51      Emile Smith Rowe   
13    2021-08-13        Arsenal           2      60  Albert Sambi Lokonga   
14    2021-08-13        Arsenal           2      64        Kieran Tierney   
15    2021-08-13        Arsenal           2      65            Martinelli   
16    2021-08-13      Brentford           2      66           Sergi Canós   
17    2021-08-13        Arsenal           2      68        Calum Chambers   
18    2021-08-13        Arsenal           2      70          Granit Xhaka   
19    2021-08-13      Brentford           2      73    Christian Nørgaard   
20    2021-08-13        Arsenal           2      76        Kieran Tierney   
21    2021-08-13        Arsenal           2      77          Nicolas Pépé   
22    2021-08-13      Brentford           2      80    Christian Nørgaard   
23    2021-08-13        Arsenal           2      83          Nuno Tavares   
24    2021-08-13        Arsenal           2      86          Granit Xhaka   
25    2021-08-13        Arsenal           2      87          Nicolas Pépé   
26    2021-08-13        Arsenal           2      87            Pablo Marí   
27    2021-08-13        Arsenal           2      91  Albert Sambi Lokonga   
28    2021-08-13        Arsenal           2      92          Reiss Nelson   
29    2021-08-13        Arsenal           2      92      Emile Smith Rowe   
...          ...            ...         ...     ...                   ...   
9697  2022-05-22  Newcastle Utd           2      85         Callum Wilson   
9698  2022-05-22        Burnley           2      88         Maxwel Cornet   
9699  2022-05-22  Newcastle Utd           2      90         Callum Wilson   
9700  2022-05-22        Chelsea           1       5           Kai Havertz   
9701  2022-05-22        Chelsea           1       9                Kenedy   
9702  2022-05-22        Chelsea           1       9           Saúl Ñíguez   
9703  2022-05-22        Chelsea           1       9           Mason Mount   
9704  2022-05-22        Chelsea           1      11           Kai Havertz   
9705  2022-05-22        Watford           1      14        Moussa Sissoko   
9706  2022-05-22        Chelsea           1      15           Saúl Ñíguez   
9707  2022-05-22        Chelsea           1      21           Mason Mount   
9708  2022-05-22        Watford           1      25         Tom Cleverley   
9709  2022-05-22        Watford           1      25           Edo Kayembe   
9710  2022-05-22        Watford           1      31          Kiko Femenía   
9711  2022-05-22        Chelsea           1      39           Mason Mount   
9712  2022-05-22        Chelsea           1      40           Kai Havertz   
9713  2022-05-22        Chelsea           1      44           Mason Mount   
9714  2022-05-22        Chelsea           1      46           Kai Havertz   
9715  2022-05-22        Watford           2      48            João Pedro   
9716  2022-05-22        Watford           2      50              Ken Sema   
9717  20

# save data

In [416]:
fb.to_csv('eng1_2122_shooting_data_xG.csv', index = False)